#!/usr/bin/env bash
set -euo pipefail

# Push all env and voice config to the VPS in one script.
# Sends: merged .env (public + secrets), .env.secrets, and voice-phrases.json.
# Public config: deploy/public.env.<env>. Secrets: .env.secrets (repo root).
# Optional: deploy/.env.<env> for per-environment overrides.
#
# Usage: ./scripts/push-env.sh <staging|production> [user@host]
#
# Examples:
#   ./scripts/push-env.sh staging
#   ./scripts/push-env.sh staging deploy@198.51.100.1
#   ./scripts/push-env.sh production deploy@my-vps.example.com

ENV="${1:?Usage: push-env.sh <staging|production> [user@host]}"
VPS="${2:-deploy@${VPS_HOST:?Set VPS_HOST env var or pass user@host as second arg}}"

if [[ "$ENV" != "production" && "$ENV" != "staging" ]]; then
  echo "Error: environment must be 'staging' or 'production'" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}/.."
LOCAL_PUBLIC_ENV="${REPO_ROOT}/deploy/public.env.${ENV}"
LOCAL_SECRETS="${REPO_ROOT}/.env.secrets"
LOCAL_ENV_OVERRIDES="${REPO_ROOT}/deploy/.env.${ENV}"
REMOTE_DIR="/opt/collective-will/${ENV}"
REMOTE_PATH="${REMOTE_DIR}/.env"
REMOTE_SECRETS="${REMOTE_DIR}/.env.secrets"
LOCAL_VOICE_PHRASES="${REPO_ROOT}/voice-phrases.json"
REMOTE_VOICE_PHRASES="${REMOTE_DIR}/voice-phrases.json"
TMP_MERGED_ENV="$(mktemp)"
TMP_SECRETS="$(mktemp)"

cleanup() {
  rm -f "$TMP_MERGED_ENV" "$TMP_SECRETS"
}
trap cleanup EXIT

if [[ ! -f "$LOCAL_PUBLIC_ENV" ]]; then
  echo "Error: ${LOCAL_PUBLIC_ENV} not found" >&2
  exit 1
fi

if [[ ! -f "$LOCAL_SECRETS" ]]; then
  echo "Error: ${LOCAL_SECRETS} not found. Create from .env.secrets.example and fill in values." >&2
  exit 1
fi

if [[ ! -f "$LOCAL_VOICE_PHRASES" ]]; then
  echo "Warning: ${LOCAL_VOICE_PHRASES} not found. Voice verification will fail until you push it." >&2
fi

# Merge secrets: .env.secrets base, then deploy/.env.<env> overrides (if present)
cp "$LOCAL_SECRETS" "$TMP_SECRETS"
if [[ -f "$LOCAL_ENV_OVERRIDES" ]]; then
  echo "==> Applying per-env overrides from ${LOCAL_ENV_OVERRIDES}"
  awk -F= '
    FNR == NR {
      if ($0 ~ /^[[:space:]]*#/ || $0 ~ /^[[:space:]]*$/) next
      key = $1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      override_keys[key] = $0
      next
    }
    {
      if ($0 ~ /^[[:space:]]*#/ || $0 ~ /^[[:space:]]*$/) { print; next }
      key = $1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key in override_keys) {
        print override_keys[key]
        next
      }
      print
    }
  ' "$LOCAL_ENV_OVERRIDES" "$TMP_SECRETS" > "${TMP_SECRETS}.tmp"
  mv "${TMP_SECRETS}.tmp" "$TMP_SECRETS"
fi

# Merge public + secrets (public keys take precedence, deploy.sh style)
awk -F= '
  FNR == NR {
    if ($0 ~ /^[[:space:]]*#/ || $0 ~ /^[[:space:]]*$/) next
    key = $1
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    public_keys[key] = 1
    next
  }
  {
    if ($0 ~ /^[[:space:]]*#/ || $0 ~ /^[[:space:]]*$/) { print; next }
    key = $1
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
    if (key in public_keys) { next }
    print
  }
' "$LOCAL_PUBLIC_ENV" "$TMP_SECRETS" > "${TMP_MERGED_ENV}.secrets"

{
  echo "# Autogenerated by scripts/push-env.sh (${ENV})"
  echo "# Source: deploy/public.env.${ENV} + .env.secrets"
  [[ -f "$LOCAL_ENV_OVERRIDES" ]] && echo "# Overrides: deploy/.env.${ENV}"
  echo
  cat "$LOCAL_PUBLIC_ENV"
  echo
  cat "${TMP_MERGED_ENV}.secrets"
} > "$TMP_MERGED_ENV"
rm -f "${TMP_MERGED_ENV}.secrets"

echo "==> Pushing env and secrets to ${VPS}:${REMOTE_DIR}"

ssh "$VPS" "mkdir -p ${REMOTE_DIR}"

# Merged .env (public + secrets) for standalone use / legacy deploy source
echo "==> Pushing merged .env (deploy/public.env.${ENV} + .env.secrets)"
scp "$TMP_MERGED_ENV" "${VPS}:${REMOTE_PATH}"
ssh "$VPS" "chmod 600 ${REMOTE_PATH}"

# .env.secrets so deploy.sh can merge with public during deploy
echo "==> Pushing .env.secrets"
scp "$LOCAL_SECRETS" "${VPS}:${REMOTE_SECRETS}"
ssh "$VPS" "chmod 600 ${REMOTE_SECRETS}"

# Voice phrase pool (required for voice verification)
# 644 so the backend container (runs as non-root) can read the file when mounted
if [[ -f "$LOCAL_VOICE_PHRASES" ]]; then
  echo "==> Pushing voice-phrases.json"
  scp "$LOCAL_VOICE_PHRASES" "${VPS}:${REMOTE_VOICE_PHRASES}"
  ssh "$VPS" "chmod 644 ${REMOTE_VOICE_PHRASES}"
else
  echo "==> Skipping voice-phrases.json (file not found; copy voice-phrases.json.example and fill to enable voice)"
fi

echo "==> Done. Verifying..."
ssh "$VPS" "echo '.env:' && wc -l ${REMOTE_PATH} && ls -la ${REMOTE_PATH} && echo '.env.secrets:' && wc -l ${REMOTE_SECRETS} && ls -la ${REMOTE_SECRETS}"
if [[ -f "$LOCAL_VOICE_PHRASES" ]]; then
  ssh "$VPS" "echo 'voice-phrases.json:' && wc -l ${REMOTE_VOICE_PHRASES} && ls -la ${REMOTE_VOICE_PHRASES}"
fi
